---
volumes: 
  data01:
    driver: local

networks:
  fleet:

services:
  fleet: 
    image: fleetdm/fleet
    depends_on:
      - mysql
    platform: linux/x86_64
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    env_file: fleet/default.env
    networks:
      - fleet
    expose: 
      - 8412
    volumes:
      - ./fleet:/fleet/
      - ./fleet/logs:/logs
      - ./fleet/vulndb:/vulndb
      
  mysql: 
    image: mysql
    platform: linux/x86_64
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file: mysql/default.env
    cap_add:
      - SYS_NICE
    expose:
      - 3306
    networks:
      - fleet

  redis:
    image: redis
    depends_on:
      - mysql
    expose:
      - 6379
    networks:
      - fleet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fleet
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.3
    networks:
      - fleet
    volumes:
      - ./fleet/logs:/fleet/logs
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat:/filebeat

