---
volumes: 
  data01:
    driver: local

networks:
  fleet:

services:
  fleet: 
    image: fleetdm/fleet
    depends_on:
      - mysql
    platform: linux/x86_64
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    env_file: fleet/default.env
    labels:
      - traefik.enable=true
      - "traefik.http.services.fleet.loadbalancer.server.port=8412"
      - "traefik.http.routers.fleet.entrypoints=https"
      - "traefik.http.routers.fleet-tls.tls.domains[0].main=fleet.traefik.me"
      - "traefik.http.routers.fleet-tls.tls.domains[0].sans=fleet-*.traefik.me"
    networks:
      - fleet
    expose: 
      - 8412
    volumes:
      - ./fleet:/fleet/
      - ./fleet/logs:/logs
      - ./fleet/vulndb:/vulndb
      - ./certs:/certs
  
  mysql: 
    image: mysql
    depends_on:
      - traefik
    platform: linux/x86_64
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file: mysql/default.env
    cap_add:
      - SYS_NICE
    expose:
      - 3306
    networks:
      - fleet

  redis:
    image: redis
    depends_on:
      - mysql
    expose:
      - 6379
    networks:
      - fleet
   
  traefik:
    restart: unless-stopped
    image: traefik:v2.0.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

    volumes:
      - ./traefik:/etc/traefik
      - ./certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fleet
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.3
    networks:
      - fleet
    volumes:
      - ./fleet/logs:/fleet/logs
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat:/filebeat



  # helper:
  #   image: alpine
  #   command: sh -c "cd /etc/ssl/traefik
  #     && wget traefik.me/cert.pem -O cert.pem
  #     && wget traefik.me/privkey.pem -O privkey.pem"
  #   volumes:
  #     - ./certs:/etc/ssl/traefik

